import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/lib/react-query";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "GlitchLink",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>{" "}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
